Repository Riverscapes/RiverscapesXML, pull requests merged in 2021-09, with the labels that each got.

#238 pyRCA project file support
  Projects/XSD/V1/RCA.xsd
  Projects/examples/RCA.xml
Labels: enhancement

#241 Add report to TauDEM BL
  RaveBusinessLogic/TauDEM.xml
Labels: BusinessLogic, pkg:TauDEM

#239 BEF should accept HUC8,10 and 12
  Programs/BEF/Program.xml
Labels: :bug: bug

#259 New program USFWS
  Programs/USFWS/Program.xml
Labels: enhancement

#255 Removing HANDfrom all programs now that we have TauDEM
  Programs/Anabranch/Program.xml
  Programs/AsotinIMW/Program.xml
  Programs/BLM/Program.xml
  Programs/Store/NAR.xml
  Programs/Store/Public.xml
  Projects/XSD/V1/HAND.xsd
  Projects/examples/HAND.xml
  RaveBusinessLogic/HAND.xml
Labels: enhancement, pkg:TauDEM

#268 Updated pyRCAT Business Logic
  RaveBusinessLogic/RCA.xml
Labels: BusinessLogic

#272 Changes to BL to expose geopackages
  RaveBusinessLogic/BRAT.xml
Labels: BusinessLogic, pkg:BRAT

#264 Web rave brat curation
  Symbology/web/BRAT/veg_suitability.clr
Labels: :globe_with_meridians: WebRAVE

#279 Curated webRAVE symbology for RS_Context
  Symbology/web/RSContext/nhdephemeral.json
  Symbology/web/RSContext/ownership.json
  Symbology/web/RSContext/upstreamdrainagearea.json
  Symbology/web/Shared/bankfull_flowlines.json
  Symbology/web/Shared/canals_ditches.json
  Symbology/web/Shared/drainage_area.txt
  Symbology/web/Shared/flow_lines.json
  Symbology/web/Shared/pipes.json
Labels: :globe_with_meridians: WebRAVE
